datas:
  name: datas
  image: busybox
  volumes:
    - /datas

php:
  build: .
  dockerfile: dockerfiles/php/Dockerfile
  volumes:
    - .:/app
  links:
    - mysql

composer:
  image: composer/composer
  volumes:
    - .:/app

mysql:
  hostname: mysql
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_DATABASE: "models"
  ports:
    - "3306"